services:
  postgres:
    image: postgres:17.5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: pg_isready -U postgres -d postgres
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5

  i-s-i-t:
    build:
      context: ../..
      dockerfile: backend/ISIT/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    env_file:
      - .env

volumes:
  postgres_data:
